<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Ical.Net" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EventFinder.Core\EventFinder.Core.csproj" />
    <ProjectReference Include="..\..\src\EventFinder.Data\EventFinder.Data.csproj" />
    <ProjectReference Include="..\..\src\EventFinder.Ingestion\EventFinder.Ingestion.csproj" />
    <ProjectReference Include="..\..\src\EventFinder.Api\EventFinder.Api.csproj" />
  </ItemGroup>

</Project>
